baseurl = "https://theobsoletemarketer.com"
metaDataFormat = "yaml"
title = "The Obsolete Marketer"
theme = "blist"
enableEmoji = true

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "Learn to use the marketing AI that may one day replace you" 
      introSubtitle = "I explore technology that helps time-strapped marketers increase productivity, find new ideas, and avoid overwhelm. Pick any post below to start."
      introPhoto = "/robot-opt.jpg"
      logo = "/obsolete-marketer-logo.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    #[[languages.en.menu.main]]
    #    name = "Tags"
    #    url = "tags"
    #    weight = 3

    [[languages.en.menu.main]]
        name = "Top Post"
        url = "/en/blog/emoji-support/"
        weight = 3

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 – The Obsolete Marketer – All rights reserved"
  favicon = "/tom-favicon.ico"

  # Background color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-green-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

[params.homepage.social]
  # Global params common for both languages
  title = "Clearly, what's above wasn't enough"
  description = "Add some marketing AI and automation to your social feed"
  twitter = "https://twitter.com/gocentas_"
  linkedin = "https://linkedin.com/in/gocentas"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
