baseurl = "https://theobsoletemarketer.com"
metaDataFormat = "yaml"
title = "The Obsolete Marketer"
theme = "blist"

DefaultContentLanguage = "en"
DefaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    contentDir = "content/en" #English
    weight = 1
    languageName = "English"
    [languages.en.params]
      introTitle = "The Obsolete Marketer"
      introSubtitle = "Helping marketers to tame their robot overlords"
      introPhoto = "/robot-opt.jpg"
      logo = "/obsolete-marketer-logo.png"
    [[languages.en.menu.main]]
        name = "Blog"
        url = "blog"
        weight = 1

    [[languages.en.menu.main]]
        name = "About"
        url = "page/about/"
        weight = 2

    [[languages.en.menu.main]]
        name = "Tags"
        url = "tags"
        weight = 3

    [[languages.en.menu.main]]
        name = "Top Post"
        url = "/en/blog/emoji-support/"
        weight = 4

[params]
  # Enable the darkmode toggle in header
  darkModeToggle = true
  
  # Enable search in header
  enableSearch = true

  # Custom copyright - optional
  copyright = "Copyright © 2022 – The Obsolete Marketer – All rights reserved"
  favicon = "/favicon.png"

  # Background color for the intro details and social links block, not applicable for dark mode
  # Supported values: Any color from TailwindCSS default colors
  # Reference: https://tailwindcss.com/docs/customizing-colors
  ascentColor = "bg-green-100"

  # The page bundle that is shown on the front page
  frontBundle = "blog"

[params.homepage.social]
  # Global params common for both languages
  title = "Follow me"
  description = "I'm not even sure where this text goes"
  twitter = "https://twitter.com/gocentas_"
  linkedin = "https://linkedin.com/in/gocentas"

[[menu.main]]
  name = "About"
  url = "/about"

[build]
  writeStats = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
